llama_path: '/userhome/models/Llama-3.1-8B-Instruct'
speech_model_path: '/userhome/models/wavlm-large-st'
llama_hidden_size: 4096
is_peft: False
# data
batch_size: 16
libri_root: '/userhome/datasets/LibriSpeech'
librispeech_meta: 'data/librispeech'

is_asr: True
task_set: []
# task_set: ['continue', 'rewrite', 'select_v', 'select_n']
# task_set: ['translate_bi', 'snips_bi', 'fluent_bi', 'asr']
meta_path: '/userhome/datasets/meta_data'
train_bucket: ['train-clean-100', 'train-clean-360', 'train-other-500']
eval_bucket: ['test-clean']

iemo_root: '/userhome/datasets/IEMOCAP_full_release'
iemo_meta: '/userhome/datasets/meta_data/iemo_data'
iemo_eval: 'Session5'


fluent_root: '/userhome/datasets/fluent_speech_commands_dataset'
snips_root: '/userhome/datasets/snips'
translate_root: 'C:\Users\LeMU_Haruka\Downloads'